### ISSUE TITLE
All question-answer pairs of S10 QA and Smart TV/remote QA?

### ISSUE THREAD

**Issue by zhangliang-04** [anon-submission2020/Anonymous-Submission-EMNLP2021#1]
Hi,
It seems that the [data](https://github.com/abhi1nandy2/EMNLP-2021-Findings/tree/main/data) only contains 50 QA samples for S10 QA and 684 samples for Smart TV/remote QA. Is the full dataset available?

**Comment by abhi1nandy2** [comment]
Thank you for interest in our paper. Sorry for the late reply. 

The link to the entire corpus can be found here - https://drive.google.com/drive/folders/1-gX1DlmVodP6OVRJC3WBRZoGgxPuJvvt 

The project website is - https://sites.google.com/view/emanualqa/home 

Also, since this project was in collaboration with Samsung, we are unable to provide with the full S10 QA Dataset at this time. However, the questions follow the format of data/smart_remote_QA.zip, and I would request you to use that for the time being. Also, if you would like to use our code/data, we request you to cite our paper.

**Comment by h366lj3** [comment]
Hi @abhi1nandy2 , for the released 50 QA samples for S10 QA and 684 samples for Smart TV/remote QA, I could not locate a clear indication of any sort of license terms. Can you please put a license for that? Thanks!
